import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = (process.argv[2] === "production");

esbuild.build({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    // 這裡使用萬用字元，強制排除所有 @codemirror 開頭的東西
    external: [
        "obsidian",
        "electron",
        "@codemirror/*", 
        "fs", "path", "url"
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
}).catch(() => process.exit(1));
